### ISSUE TITLE
Compile Error - sending invitation.....no answer...?

### ISSUE THREAD

**Issue by SV-Krishna** [Basseltan/NMEA0183-Level-Sensor-DS1603L#1]
Hello

Many thanks for this project. However I get the following compile error in platformio, using a generic wemos mini 8266 board.

![image](https://github.com/Basseltan/NMEA0183-Level-Sensor-DS1603L/assets/145610483/6bec99ed-3c90-4d05-aec2-7ea1a67d7eba)

**Comment by Basseltan** [comment]
Hi SV-Krishna, 
Sorry for answering so late - I have been very busy the last days. 

What I see in your screenshot is, that you are trying to upload the firmware.bin via OTA (over the air update) and the Board with the IP address 192.168.179.97 wasn´t found. Do you want to use OTA? Otherwise you have to select another upload method. 
Long story short: It's not a compile error, it's an error during the firmware upload.
BR
Basseltan

**Comment by SV-Krishna** [comment]
Please don't worry and good to hear from you. I had actually deleted the project. So I created it again from scratch, tried to compile the project in platformio and the compile failed. Here's a screen shot of some of the errors.

![image](https://github.com/Basseltan/NMEA0183-Level-Sensor-DS1603L/assets/145610483/e4b22f7b-9e37-4045-9d20-a57407f635c6)

**Comment by Basseltan** [comment]
The code above isn't from my project. 
The error occurs because there is an include in ultrasonic_level.cpp for sensor.h that cannot be found. All you have to know is written in the error message. Install the library in the correct path or adapt the path and the compiler will go further.

**Comment by SV-Krishna** [comment]
Hi Basseltan, its a real shame, resolving this issue, try to compile and PlatformIO then goes on to flag another 73 problems, with the compile failing overall. 

Shame as great concept.
